project_id = "yqzjsmqrtxwaxqzyhxki"

[functions.seed-blogs]
verify_jwt = false

[functions.send-monthly-marketing-report]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.payment-reminder]
verify_jwt = false

[functions.submit-lead]
verify_jwt = false

[functions.generate-blog-image]
verify_jwt = false

[functions.send-negative-balance-reminders]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-test-emails]
verify_jwt = false

[functions.process-email-campaign]
verify_jwt = false

[functions.generate-lesson-scene]
verify_jwt = false
