project_id = "rahpkflknkofuuhnbfyc"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.payment-reminder]
verify_jwt = false

[functions.submit-lead]
verify_jwt = false

[functions.generate-blog-image]
verify_jwt = false
