import jsPDF from "jspdf";
import type { AdvisorResult } from "@/types/analysis";

export function downloadAdvisorPDF(result: AdvisorResult, goal: "job" | "travel") {
  const doc = new jsPDF();
  const margin = 20;
  const maxWidth = doc.internal.pageSize.getWidth() - margin * 2;
  let y = 20;

  const checkPage = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - 20) { doc.addPage(); y = 20; }
  };

  const addTitle = (text: string) => {
    checkPage(15);
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(text, margin, y);
    y += 10;
  };

  const addSubtitle = (text: string) => {
    checkPage(12);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text(text, margin, y);
    y += 8;
  };

  const addBody = (text: string) => {
    checkPage(10);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(text, maxWidth);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 4;
  };

  const addBullet = (text: string) => {
    checkPage(8);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(text, maxWidth - 8);
    doc.text("•", margin, y);
    doc.text(lines, margin + 6, y);
    y += lines.length * 5 + 2;
  };

  // Header
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(goal === "job" ? "Career Advisor Report" : "Travel & Remote Work Report", margin, y);
  y += 8;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120);
  doc.text(`Generated by GrowthCV — ${new Date().toLocaleDateString()}`, margin, y);
  doc.setTextColor(0);
  y += 14;

  addTitle("Career Path Assessment");
  addBody(result.pathAdvice);
  y += 4;

  addTitle(goal === "job" ? "Top Countries for Jobs" : "Top Countries for You");
  result.topCountries?.forEach((c, i) => {
    checkPage(40);
    addSubtitle(`${i + 1}. ${c.country}`);
    addBody(c.reason);
    if (c.avgSalary) addBody(`Salary Range: ${c.avgSalary}`);
    if (c.costOfLiving) addBody(`Cost of Living: ${c.costOfLiving}/month`);
    addBody(`Visa: ${c.visaInfo}`);
    if (c.searchPlatforms?.length) addBody(`Job Platforms: ${c.searchPlatforms.join(", ")}`);
    y += 2;
  });

  addTitle("Action Steps");
  result.actionSteps?.forEach((step, i) => addBullet(`${i + 1}. ${step}`));
  y += 4;

  addTitle("Skills to Learn");
  result.skillsToLearn?.forEach((skill) => addBullet(skill));
  y += 4;

  result.decisions?.forEach((d) => {
    checkPage(30);
    addTitle(d.question);
    addSubtitle("Pros:");
    d.pros?.forEach((p) => addBullet(p));
    addSubtitle("Cons:");
    d.cons?.forEach((c) => addBullet(c));
    addSubtitle("Verdict:");
    addBody(d.verdict);
    y += 4;
  });

  doc.save(`GrowthCV-${goal}-advice.pdf`);
}
