import jsPDF from "jspdf";
import type { AnalysisResult } from "@/types/analysis";

export function downloadCVReportPDF(result: AnalysisResult) {
  const doc = new jsPDF();
  const margin = 20;
  const maxWidth = doc.internal.pageSize.getWidth() - margin * 2;
  let y = 20;

  const checkPage = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - 20) { doc.addPage(); y = 20; }
  };

  const addTitle = (text: string) => {
    checkPage(15);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(text, margin, y);
    y += 10;
  };

  const addBody = (text: string) => {
    checkPage(10);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(text, maxWidth);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 4;
  };

  const addBullet = (text: string) => {
    checkPage(8);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(text, maxWidth - 8);
    doc.text("•", margin, y);
    doc.text(lines, margin + 6, y);
    y += lines.length * 5 + 2;
  };

  // Header
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("CV Analysis Report", margin, y);
  y += 8;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120);
  doc.text(`Generated by GrowthCV — ${new Date().toLocaleDateString()}`, margin, y);
  doc.setTextColor(0);
  y += 14;

  addTitle(`Overall Score: ${result.overallScore}/100`);
  addBody(result.summary);
  y += 4;

  if (result.topFixes?.length) {
    addTitle("Top Things to Fix");
    result.topFixes.forEach((fix, i) => addBullet(`${i + 1}. ${fix}`));
    y += 4;
  }

  addTitle("Detailed Breakdown");
  result.categories?.forEach((cat) => {
    checkPage(25);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(`${cat.name} — ${cat.score}/100 (${cat.status})`, margin, y);
    y += 7;
    addBody(cat.feedback);
    cat.fixes?.forEach((fix) => addBullet(`→ ${fix}`));
    y += 2;
  });

  if (result.strengths?.length) {
    addTitle("Strengths");
    result.strengths.forEach((s) => addBullet(s));
    y += 4;
  }

  if (result.modernTips?.length) {
    addTitle("Modern Hiring Tips");
    result.modernTips.forEach((t) => addBullet(t));
    y += 4;
  }

  if (result.improvements?.length) {
    addTitle("Improvements Made");
    result.improvements.forEach((imp) => addBullet(`✓ ${imp}`));
  }

  doc.save("GrowthCV-Analysis-Report.pdf");
}
