import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  MessageSquare, Loader2, Eye, EyeOff,
  Brain, Wrench, Users, Lightbulb, Target, Download, CheckCircle,
  ArrowRight, ArrowLeft, Star, Sparkles, ThumbsUp, AlertCircle
} from "lucide-react";
import jsPDF from "jspdf";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import type { InterviewQuestion } from "@/types/analysis";

interface AnswerFeedback {
  score: number;
  summary: string;
  strengths: string[];
  improvements: string[];
  improvedAnswer: string;
}

interface InterviewPracticeProps {
  questions: InterviewQuestion[];
  isLoading: boolean;
  onStart: () => void;
  hasStarted: boolean;
}

const categoryConfig = {
  behavioral: { icon: Users, label: "Behavioral", color: "bg-primary/10 text-primary border-primary/20" },
  technical: { icon: Wrench, label: "Technical", color: "bg-secondary text-secondary-foreground border-border" },
  personality: { icon: Brain, label: "Personality", color: "bg-accent/10 text-accent border-accent/20" },
  situational: { icon: Lightbulb, label: "Situational", color: "bg-primary/15 text-primary border-primary/25" },
  motivation: { icon: Target, label: "Motivation", color: "bg-accent/15 text-accent border-accent/25" },
};

const difficultyColors = {
  easy: "bg-accent/10 text-accent",
  medium: "bg-primary/10 text-primary",
  hard: "bg-destructive/10 text-destructive",
};

function getScoreColor(score: number) {
  if (score >= 8) return "text-accent";
  if (score >= 5) return "text-primary";
  return "text-destructive";
}

function getScoreBg(score: number) {
  if (score >= 8) return "bg-accent/10 border-accent/20";
  if (score >= 5) return "bg-primary/10 border-primary/20";
  return "bg-destructive/10 border-destructive/20";
}

function downloadInterviewPDF(questions: InterviewQuestion[], answers: Record<string, string>, feedbacks: Record<string, AnswerFeedback>) {
  const doc = new jsPDF();
  const margin = 20;
  const maxWidth = doc.internal.pageSize.getWidth() - margin * 2;
  let y = 20;

  const checkPage = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - 20) { doc.addPage(); y = 20; }
  };

  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("Interview Practice Notes", margin, y);
  y += 8;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120);
  doc.text(`Generated by GrowthCV — ${new Date().toLocaleDateString()}`, margin, y);
  doc.setTextColor(0);
  y += 14;

  questions.forEach((q, i) => {
    checkPage(40);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    const qLines = doc.splitTextToSize(`${i + 1}. [${q.category.toUpperCase()}] ${q.question}`, maxWidth);
    doc.text(qLines, margin, y);
    y += qLines.length * 5 + 4;

    if (answers[q.id]) {
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(50);
      const aLines = doc.splitTextToSize(`Your Answer: ${answers[q.id]}`, maxWidth);
      checkPage(aLines.length * 5 + 4);
      doc.text(aLines, margin, y);
      y += aLines.length * 5 + 4;
    }

    const fb = feedbacks[q.id];
    if (fb) {
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0);
      checkPage(10);
      doc.text(`AI Score: ${fb.score}/10 — ${fb.summary}`, margin, y);
      y += 6;

      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(60);
      fb.strengths.forEach(s => {
        const lines = doc.splitTextToSize(`✓ ${s}`, maxWidth);
        checkPage(lines.length * 5 + 2);
        doc.text(lines, margin, y);
        y += lines.length * 5 + 2;
      });
      fb.improvements.forEach(imp => {
        const lines = doc.splitTextToSize(`→ ${imp}`, maxWidth);
        checkPage(lines.length * 5 + 2);
        doc.text(lines, margin, y);
        y += lines.length * 5 + 2;
      });
      y += 2;
    }

    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(100);
    const hLines = doc.splitTextToSize(`Tip: ${q.hint}`, maxWidth);
    checkPage(hLines.length * 5 + 4);
    doc.text(hLines, margin, y);
    doc.setTextColor(0);
    y += hLines.length * 5 + 6;
  });

  doc.save("GrowthCV-Interview-Practice.pdf");
}

function FeedbackDisplay({ feedback }: { feedback: AnswerFeedback }) {
  return (
    <motion.div
      initial={{ opacity: 0, height: 0 }}
      animate={{ opacity: 1, height: "auto" }}
      exit={{ opacity: 0, height: 0 }}
      className={`rounded-xl border p-5 space-y-3 ${getScoreBg(feedback.score)}`}
    >
      <div className="flex items-center gap-4">
        <div className={`text-3xl font-display font-extrabold ${getScoreColor(feedback.score)}`}>
          {feedback.score}/10
        </div>
        <p className="text-sm text-foreground font-medium flex-1 leading-relaxed">{feedback.summary}</p>
      </div>

      <div className="grid gap-3 sm:grid-cols-2">
        <div className="space-y-1.5">
          <p className="text-xs font-bold text-foreground flex items-center gap-1.5">
            <ThumbsUp className="w-3.5 h-3.5 text-accent" /> Strengths
          </p>
          {feedback.strengths.map((s, i) => (
            <p key={i} className="text-xs text-muted-foreground">✓ {s}</p>
          ))}
        </div>
        <div className="space-y-1.5">
          <p className="text-xs font-bold text-foreground flex items-center gap-1.5">
            <AlertCircle className="w-3.5 h-3.5 text-primary" /> To Improve
          </p>
          {feedback.improvements.map((imp, i) => (
            <p key={i} className="text-xs text-muted-foreground">→ {imp}</p>
          ))}
        </div>
      </div>

      <details className="group">
        <summary className="text-xs font-bold text-primary cursor-pointer hover:underline flex items-center gap-1.5">
          <Sparkles className="w-3.5 h-3.5" /> View improved answer
        </summary>
        <p className="mt-2 text-xs text-muted-foreground bg-background/50 rounded-lg p-3 border border-border leading-relaxed">
          {feedback.improvedAnswer}
        </p>
      </details>
    </motion.div>
  );
}

export function InterviewPractice({ questions, isLoading, onStart, hasStarted }: InterviewPracticeProps) {
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [showHints, setShowHints] = useState<Record<string, boolean>>({});
  const [showSample, setShowSample] = useState<Record<string, boolean>>({});
  const [activeCategory, setActiveCategory] = useState<string | null>(null);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [mode, setMode] = useState<"browse" | "practice">("browse");
  const [feedbacks, setFeedbacks] = useState<Record<string, AnswerFeedback>>({});
  const [scoringId, setScoringId] = useState<string | null>(null);

  const scoreAnswer = async (q: InterviewQuestion) => {
    const answer = answers[q.id];
    if (!answer?.trim()) {
      toast.error("Write an answer first before scoring.");
      return;
    }
    setScoringId(q.id);
    try {
      const { data, error } = await supabase.functions.invoke("score-interview-answer", {
        body: {
          question: q.question,
          userAnswer: answer,
          sampleAnswer: q.sampleAnswer,
          category: q.category,
          difficulty: q.difficulty,
        },
      });
      if (error) throw error;
      if (data.error) throw new Error(data.error);
      setFeedbacks(prev => ({ ...prev, [q.id]: data }));
    } catch (e: any) {
      console.error("Scoring error:", e);
      toast.error(e.message || "Failed to score answer.");
    } finally {
      setScoringId(null);
    }
  };

  if (!hasStarted) {
    return (
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
        <div className="text-center mb-2">
          <div className="section-divider mb-6" />
          <h2 className="font-display text-2xl md:text-3xl font-extrabold text-foreground flex items-center justify-center gap-3">
            <MessageSquare className="w-7 h-7 text-primary" />
            Interview Practice
          </h2>
          <p className="text-muted-foreground mt-2">Practice real interview questions tailored to your CV and skills</p>
        </div>
        <div className="flex justify-center">
          <button
            onClick={onStart}
            disabled={isLoading}
            className="btn-premium disabled:opacity-50 disabled:hover:translate-y-0"
          >
            {isLoading ? (
              <><Loader2 className="w-5 h-5 animate-spin" /> Generating Questions...</>
            ) : (
              <><MessageSquare className="w-5 h-5" /> Start Interview Practice</>
            )}
          </button>
        </div>
      </motion.div>
    );
  }

  if (isLoading) {
    return (
      <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex flex-col items-center justify-center py-16 gap-4">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
        <p className="text-muted-foreground font-medium">Generating personalized interview questions...</p>
      </motion.div>
    );
  }

  const categories = [...new Set(questions.map((q) => q.category))];
  const filtered = activeCategory ? questions.filter((q) => q.category === activeCategory) : questions;
  const practiceQuestion = filtered[currentIndex];
  const answeredCount = Object.values(answers).filter(Boolean).length;
  const scoredCount = Object.keys(feedbacks).length;

  return (
    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <h2 className="font-display text-2xl font-extrabold text-foreground flex items-center gap-3">
          <MessageSquare className="w-6 h-6 text-primary" /> Interview Practice
        </h2>
        <div className="flex items-center gap-3 flex-wrap">
          <span className="text-sm text-muted-foreground font-mono">{answeredCount}/{questions.length} answered</span>
          {scoredCount > 0 && (
            <span className="text-sm text-primary font-bold flex items-center gap-1">
              <Star className="w-3.5 h-3.5" /> {scoredCount} scored
            </span>
          )}
          <button
            onClick={() => downloadInterviewPDF(questions, answers, feedbacks)}
            className="flex items-center gap-2 px-4 py-2 rounded-lg border border-border bg-card text-foreground font-medium text-sm hover:bg-muted transition-all hover:shadow-md"
          >
            <Download className="w-4 h-4" /> Download Notes
          </button>
        </div>
      </div>

      {/* Mode toggle */}
      <div className="flex gap-2 p-1 rounded-xl bg-muted">
        <button
          onClick={() => setMode("browse")}
          className={`flex-1 px-4 py-2.5 rounded-lg text-sm font-bold transition-all ${
            mode === "browse" ? "bg-card text-foreground shadow-md" : "text-muted-foreground hover:text-foreground"
          }`}
        >
          Browse All
        </button>
        <button
          onClick={() => { setMode("practice"); setCurrentIndex(0); }}
          className={`flex-1 px-4 py-2.5 rounded-lg text-sm font-bold transition-all ${
            mode === "practice" ? "bg-card text-foreground shadow-md" : "text-muted-foreground hover:text-foreground"
          }`}
        >
          Practice Mode
        </button>
      </div>

      {/* Category filters */}
      <div className="flex flex-wrap gap-2">
        <button
          onClick={() => { setActiveCategory(null); setCurrentIndex(0); }}
          className={`px-3.5 py-1.5 rounded-full text-xs font-bold transition-all ${
            !activeCategory ? "hero-gradient text-primary-foreground shadow-md" : "bg-secondary text-secondary-foreground hover:bg-muted"
          }`}
        >
          All ({questions.length})
        </button>
        {categories.map((cat) => {
          const config = categoryConfig[cat as keyof typeof categoryConfig];
          const count = questions.filter((q) => q.category === cat).length;
          return (
            <button
              key={cat}
              onClick={() => { setActiveCategory(cat === activeCategory ? null : cat); setCurrentIndex(0); }}
              className={`px-3.5 py-1.5 rounded-full text-xs font-bold border transition-all ${
                cat === activeCategory ? "hero-gradient text-primary-foreground border-transparent shadow-md" : config.color
              }`}
            >
              {config.label} ({count})
            </button>
          );
        })}
      </div>

      {/* Practice Mode */}
      {mode === "practice" && practiceQuestion && (
        <AnimatePresence mode="wait">
          <motion.div
            key={practiceQuestion.id}
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            className="glass-card rounded-2xl p-7 space-y-5"
          >
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className={`px-2.5 py-1 rounded-lg text-xs font-bold ${categoryConfig[practiceQuestion.category]?.color}`}>
                  {categoryConfig[practiceQuestion.category]?.label}
                </span>
                <span className={`px-2.5 py-1 rounded-lg text-xs font-bold ${difficultyColors[practiceQuestion.difficulty]}`}>
                  {practiceQuestion.difficulty}
                </span>
                {feedbacks[practiceQuestion.id] && (
                  <span className={`px-2.5 py-1 rounded-lg text-xs font-bold ${getScoreColor(feedbacks[practiceQuestion.id].score)}`}>
                    {feedbacks[practiceQuestion.id].score}/10
                  </span>
                )}
              </div>
              <span className="text-sm text-muted-foreground font-mono">{currentIndex + 1}/{filtered.length}</span>
            </div>

            <h3 className="text-lg font-display font-bold text-foreground leading-relaxed">{practiceQuestion.question}</h3>

            <textarea
              value={answers[practiceQuestion.id] || ""}
              onChange={(e) => setAnswers((prev) => ({ ...prev, [practiceQuestion.id]: e.target.value }))}
              placeholder="Type your answer here... Practice answering as you would in a real interview."
              rows={5}
              className="w-full rounded-xl border border-border bg-background p-4 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring resize-y transition-shadow hover:shadow-sm"
            />

            <div className="flex gap-4 flex-wrap">
              <button onClick={() => setShowHints((p) => ({ ...p, [practiceQuestion.id]: !p[practiceQuestion.id] }))} className="flex items-center gap-1.5 text-sm text-primary font-bold hover:underline">
                {showHints[practiceQuestion.id] ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                {showHints[practiceQuestion.id] ? "Hide Hint" : "Show Hint"}
              </button>
              <button onClick={() => setShowSample((p) => ({ ...p, [practiceQuestion.id]: !p[practiceQuestion.id] }))} className="flex items-center gap-1.5 text-sm text-primary font-bold hover:underline">
                {showSample[practiceQuestion.id] ? <EyeOff className="w-4 h-4" /> : <CheckCircle className="w-4 h-4" />}
                {showSample[practiceQuestion.id] ? "Hide Sample" : "Show Sample Answer"}
              </button>
              <button
                onClick={() => scoreAnswer(practiceQuestion)}
                disabled={scoringId === practiceQuestion.id || !answers[practiceQuestion.id]?.trim()}
                className="flex items-center gap-1.5 text-sm font-bold text-accent hover:underline disabled:opacity-40 disabled:no-underline"
              >
                {scoringId === practiceQuestion.id ? (
                  <><Loader2 className="w-4 h-4 animate-spin" /> Scoring...</>
                ) : (
                  <><Star className="w-4 h-4" /> {feedbacks[practiceQuestion.id] ? "Re-score" : "Score My Answer"}</>
                )}
              </button>
            </div>

            <AnimatePresence>
              {showHints[practiceQuestion.id] && (
                <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} exit={{ opacity: 0, height: 0 }} className="rounded-xl bg-primary/5 border border-primary/20 p-4">
                  <p className="text-sm text-muted-foreground leading-relaxed"><strong className="text-foreground">Hint:</strong> {practiceQuestion.hint}</p>
                </motion.div>
              )}
              {showSample[practiceQuestion.id] && (
                <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} exit={{ opacity: 0, height: 0 }} className="rounded-xl bg-accent/5 border border-accent/20 p-4">
                  <p className="text-sm text-muted-foreground leading-relaxed"><strong className="text-foreground">Sample Answer:</strong> {practiceQuestion.sampleAnswer}</p>
                </motion.div>
              )}
              {feedbacks[practiceQuestion.id] && (
                <FeedbackDisplay feedback={feedbacks[practiceQuestion.id]} />
              )}
            </AnimatePresence>

            <div className="flex justify-between pt-3">
              <button disabled={currentIndex === 0} onClick={() => setCurrentIndex((i) => i - 1)} className="flex items-center gap-1 px-5 py-2.5 rounded-lg text-sm font-bold bg-secondary text-secondary-foreground hover:bg-muted transition-colors disabled:opacity-40">
                <ArrowLeft className="w-4 h-4" /> Previous
              </button>
              <button disabled={currentIndex >= filtered.length - 1} onClick={() => setCurrentIndex((i) => i + 1)} className="flex items-center gap-1 px-5 py-2.5 rounded-lg text-sm font-bold bg-primary text-primary-foreground hover:opacity-90 transition-colors disabled:opacity-40">
                Next <ArrowRight className="w-4 h-4" />
              </button>
            </div>
          </motion.div>
        </AnimatePresence>
      )}

      {/* Browse Mode */}
      {mode === "browse" && (
        <div className="space-y-4">
          {filtered.map((q, i) => {
            const config = categoryConfig[q.category];
            const Icon = config?.icon || MessageSquare;
            return (
              <motion.div key={q.id} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.03 }} className="glass-card rounded-xl p-5 space-y-3 shine-border">
                <div className="flex items-start gap-3">
                  <div className="w-8 h-8 rounded-lg bg-muted flex items-center justify-center flex-shrink-0 mt-0.5">
                    <Icon className="w-4 h-4 text-muted-foreground" />
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-1.5 flex-wrap">
                      <span className={`px-2.5 py-0.5 rounded-lg text-xs font-bold ${config?.color}`}>{config?.label}</span>
                      <span className={`px-2.5 py-0.5 rounded-lg text-xs font-bold ${difficultyColors[q.difficulty]}`}>{q.difficulty}</span>
                      {answers[q.id] && <CheckCircle className="w-4 h-4 text-accent" />}
                      {feedbacks[q.id] && (
                        <span className={`px-2.5 py-0.5 rounded-lg text-xs font-bold ${getScoreColor(feedbacks[q.id].score)}`}>
                          {feedbacks[q.id].score}/10
                        </span>
                      )}
                    </div>
                    <p className="font-display font-bold text-foreground text-sm">{q.question}</p>
                  </div>
                </div>

                <textarea
                  value={answers[q.id] || ""}
                  onChange={(e) => setAnswers((prev) => ({ ...prev, [q.id]: e.target.value }))}
                  placeholder="Your answer..."
                  rows={2}
                  className="w-full rounded-lg border border-border bg-background p-3 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring resize-y transition-shadow hover:shadow-sm"
                />

                <div className="flex gap-4 flex-wrap">
                  <button onClick={() => setShowHints((p) => ({ ...p, [q.id]: !p[q.id] }))} className="text-xs text-primary font-bold hover:underline flex items-center gap-1">
                    {showHints[q.id] ? "Hide Hint" : "Show Hint"}
                  </button>
                  <button onClick={() => setShowSample((p) => ({ ...p, [q.id]: !p[q.id] }))} className="text-xs text-primary font-bold hover:underline flex items-center gap-1">
                    {showSample[q.id] ? "Hide Sample" : "Sample Answer"}
                  </button>
                  <button
                    onClick={() => scoreAnswer(q)}
                    disabled={scoringId === q.id || !answers[q.id]?.trim()}
                    className="text-xs font-bold text-accent hover:underline flex items-center gap-1 disabled:opacity-40"
                  >
                    {scoringId === q.id ? (
                      <><Loader2 className="w-3 h-3 animate-spin" /> Scoring...</>
                    ) : (
                      <><Star className="w-3 h-3" /> {feedbacks[q.id] ? "Re-score" : "Score Answer"}</>
                    )}
                  </button>
                </div>

                <AnimatePresence>
                  {showHints[q.id] && (
                    <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="text-xs text-muted-foreground bg-primary/5 rounded-lg p-3 leading-relaxed">
                      <strong>Hint:</strong> {q.hint}
                    </motion.p>
                  )}
                  {showSample[q.id] && (
                    <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="text-xs text-muted-foreground bg-accent/5 rounded-lg p-3 leading-relaxed">
                      <strong>Sample:</strong> {q.sampleAnswer}
                    </motion.p>
                  )}
                  {feedbacks[q.id] && (
                    <FeedbackDisplay feedback={feedbacks[q.id]} />
                  )}
                </AnimatePresence>
              </motion.div>
            );
          })}
        </div>
      )}
    </motion.div>
  );
}
