INSERT INTO textbook_lessons (sort_order, emoji, title_en, title_ko, title_ar, description, description_ar, book, is_published) VALUES
(1, '👋', 'Nice to Meet You', '만나서 반갑습니다', 'سعيد بلقائك', 'Classic first meeting greetings from K-Dramas', 'تحيات اللقاء الأول الكلاسيكية من الدراما', 'kdrama', true),
(2, '🙋', 'Who Are You?', '누구세요?', 'من أنت؟', 'Asking about identity and background', 'السؤال عن الهوية والخلفية', 'kdrama', true),
(3, '📱', 'Give Me Your Number', '번호 좀 알려주세요', 'أعطني رقمك', 'Exchanging contact info and casual talk', 'تبادل معلومات الاتصال والمحادثة العفوية', 'kdrama', true),
(4, '☕', 'Let''s Get Coffee', '커피 마실래요?', 'لنشرب قهوة', 'Invitations and casual meetup phrases', 'عبارات الدعوات واللقاءات العفوية', 'kdrama', true),
(5, '😅', 'Awkward Encounters', '어색한 만남', 'لقاءات محرجة', 'Misunderstandings and awkward moments', 'سوء الفهم واللحظات المحرجة', 'kdrama', true),
(6, '💗', 'I Like You', '좋아해요', 'أنا أحبك', 'Expressing feelings and confessions of love', 'التعبير عن المشاعر واعترافات الحب', 'kdrama', true),
(7, '💔', 'Heartbreak', '이별', 'انكسار القلب', 'Breakup dialogues and emotional expressions', 'حوارات الانفصال والتعبيرات العاطفية', 'kdrama', true),
(8, '😍', 'You''re Beautiful', '예쁘다', 'أنتِ جميلة', 'Compliments, flirting & sweet talk', 'المجاملات والمغازلة والكلام الحلو', 'kdrama', true),
(9, '💑', 'Date Night', '데이트', 'ليلة موعد', 'Dating vocabulary and romantic outings', 'مفردات المواعدة والنزهات الرومانسية', 'kdrama', true),
(10, '💍', 'Will You Marry Me?', '결혼해 줄래요?', 'هل تتزوجيني؟', 'Proposals and commitment expressions', 'عبارات الخطوبة والالتزام', 'kdrama', true),
(11, '👵', 'Respect Your Elders', '어른 공경', 'احترم كبارك', 'Honorific speech with parents and grandparents', 'الخطاب التشريفي مع الوالدين والأجداد', 'kdrama', true),
(12, '👫', 'Sibling Rivalry', '형제 자매', 'تنافس الأخوة', 'Brother-sister dynamics and family banter', 'ديناميكيات الأخوة والمزاح العائلي', 'kdrama', true),
(13, '🏠', 'Family Dinner', '가족 저녁 식사', 'عشاء عائلي', 'Mealtime conversations and family gatherings', 'محادثات وقت الطعام والتجمعات العائلية', 'kdrama', true),
(14, '😤', 'Family Arguments', '가족 갈등', 'خلافات عائلية', 'Conflicts, disagreements & making up', 'الصراعات والخلافات والمصالحة', 'kdrama', true),
(15, '🙏', 'Forgive Me', '용서해 주세요', 'سامحني', 'Apologies, forgiveness & emotional reconciliation', 'الاعتذارات والمسامحة والمصالحة العاطفية', 'kdrama', true),
(16, '🏢', 'First Day at Work', '첫 출근', 'أول يوم عمل', 'Office introductions and workplace basics', 'تقديم النفس في المكتب وأساسيات العمل', 'kdrama', true),
(17, '👔', 'The Boss', '사장님', 'المدير', 'Speaking to superiors and formal corporate Korean', 'التحدث مع الرؤساء والكورية الرسمية', 'kdrama', true),
(18, '🤝', 'Business Meeting', '회의', 'اجتماع عمل', 'Meeting vocabulary and presentation phrases', 'مفردات الاجتماعات وعبارات العروض', 'kdrama', true),
(19, '😰', 'Office Drama', '사내 드라마', 'دراما المكتب', 'Gossip, rivalry & workplace tension', 'النميمة والتنافس وتوتر العمل', 'kdrama', true),
(20, '🎉', 'After-Work Drinks', '회식', 'مشروبات بعد العمل', 'Hoesik culture and team bonding expressions', 'ثقافة الهويشيك وتعبيرات ترابط الفريق', 'kdrama', true),
(21, '🏃', 'Run!', '도망쳐!', 'اهرب!', 'Commands, urgent phrases & chase scenes', 'الأوامر والعبارات العاجلة ومشاهد المطاردة', 'kdrama', true),
(22, '🔍', 'The Investigation', '수사', 'التحقيق', 'Detective and crime vocabulary', 'مفردات التحقيق والجريمة', 'kdrama', true),
(23, '⚔️', 'The Showdown', '대결', 'المواجهة', 'Confrontation dialogues and dramatic threats', 'حوارات المواجهة والتهديدات الدرامية', 'kdrama', true),
(24, '🤫', 'Secrets & Lies', '비밀과 거짓말', 'الأسرار والأكاذيب', 'Deception, revealing truth & plot twists', 'الخداع وكشف الحقيقة وتقلبات القصة', 'kdrama', true),
(25, '⚖️', 'Justice', '정의', 'العدالة', 'Courtroom drama and justice-related expressions', 'دراما قاعة المحكمة وتعبيرات العدالة', 'kdrama', true),
(26, '🍜', 'Let''s Eat!', '먹자!', 'لنأكل!', 'Ordering food and reacting to delicious meals', 'طلب الطعام والتفاعل مع الوجبات اللذيذة', 'kdrama', true),
(27, '🍺', 'Drinking Culture', '술 문화', 'ثقافة الشراب', 'Soju scenes, toasts & drinking etiquette', 'مشاهد السوجو والأنخاب وآداب الشرب', 'kdrama', true),
(28, '🍳', 'Cooking Together', '같이 요리해요', 'لنطبخ معاً', 'Cooking scenes and kitchen vocabulary', 'مشاهد الطبخ ومفردات المطبخ', 'kdrama', true),
(29, '🏪', 'Convenience Store', '편의점', 'المتجر', 'Late-night snack runs and convenience store scenes', 'جولات الوجبات الليلية ومشاهد المتجر', 'kdrama', true),
(30, '🎂', 'Celebration Feast', '축하 파티', 'حفلة احتفال', 'Birthday parties, celebrations & food traditions', 'حفلات أعياد الميلاد والاحتفالات وتقاليد الطعام', 'kdrama', true);