-- Seed all 299 textbook lessons (korean-1, daily-routine, kdrama, grammar-mastery)
-- Safe to run multiple times due to ON CONFLICT DO UPDATE

INSERT INTO public.textbook_lessons
  (sort_order, emoji, title_en, title_ko, title_ar, description, description_ar, book, topik_level, is_published)
VALUES
  (1, '🔤', 'Korean Vowels', '한국어 모음', 'الحروف المتحركة', 'Learn the 10 basic Korean vowels.', 'تعلم الحروف المتحركة العشرة.', 'korean-1', 0, true),
  (2, '🔠', 'Korean Consonants', '한국어 자음', 'الحروف الساكنة', 'Master the 14 basic Korean consonants.', 'أتقن الحروف الساكنة الأربعة عشر.', 'korean-1', 0, true),
  (3, '🧱', 'Syllable Blocks', '음절 블록', 'كتل المقاطع', 'Combine consonants and vowels into syllable blocks.', 'دمج الحروف في كتل مقطعية.', 'korean-1', 0, true),
  (4, '📐', 'Final Consonants (Batchim)', '받침', 'الحرف الأخير (باتشيم)', 'Understand batchim — final consonants in syllables.', 'فهم الباتشيم.', 'korean-1', 0, true),
  (5, '📖', 'Compound Vowels', '이중 모음', 'الحروف المتحركة المركبة', 'Learn compound vowels from combining basic vowels.', 'تعلم الحروف المتحركة المركبة.', 'korean-1', 0, true),
  (6, '💨', 'Aspirated Consonants', '거센소리', 'الأصوات المنفوثة', 'Aspirated consonants: ㅋ ㅌ ㅍ ㅊ.', 'الحروف المنفوثة ㅋ ㅌ ㅍ ㅊ.', 'korean-1', 0, true),
  (7, '⚡', 'Tensed Consonants', '된소리', 'الأصوات المشددة', 'Tensed consonants: ㄲ ㄸ ㅃ ㅆ ㅉ.', 'الحروف المشددة ㄲ ㄸ ㅃ ㅆ ㅉ.', 'korean-1', 0, true),
  (8, '🎙️', 'Pronunciation Rules', '발음 규칙', 'قواعد النطق', 'Liaison, nasalization, and aspiration rules.', 'قواعد الوصل والتحنيف والنفث.', 'korean-1', 0, true),
  (9, '📚', 'Reading Practice', '읽기 연습', 'تمرين القراءة', 'Read Korean words and short phrases.', 'اقرأ الكلمات الكورية والعبارات القصيرة.', 'korean-1', 0, true),
  (10, '✏️', 'Writing Practice', '쓰기 연습', 'تمرين الكتابة', 'Practice writing Hangul syllables and words.', 'تمرن على كتابة مقاطع هانغول والكلمات.', 'korean-1', 0, true),
  (11, '👋', 'Greetings', '인사', 'التحيات', 'Essential Korean greetings for daily life.', 'التحيات الكورية الأساسية.', 'korean-1', 1, true),
  (12, '🙏', 'Farewells', '작별 인사', 'الوداع', 'Say goodbye in various contexts.', 'قل وداعاً في سياقات مختلفة.', 'korean-1', 1, true),
  (13, '🙋', 'Self Introduction', '자기소개', 'تعريف النفس', 'Introduce name, nationality, and job.', 'قدم اسمك وجنسيتك ومهنتك.', 'korean-1', 1, true),
  (14, '🔢', 'Native Korean Numbers', '순우리말 숫자', 'الأرقام الكورية الأصلية', 'Native Korean numbers 1–99.', 'الأرقام الكورية الأصلية من ١–٩٩.', 'korean-1', 1, true),
  (15, '💯', 'Sino-Korean Numbers', '한자어 숫자', 'الأرقام الصينية الكورية', 'Numbers for money, floors, and dates.', 'أرقام المال والطوابق والتواريخ.', 'korean-1', 1, true),
  (16, '📅', 'Days of the Week', '요일', 'أيام الأسبوع', 'Name the seven days and schedule events.', 'سمِّ الأيام السبعة وجدوِل الأحداث.', 'korean-1', 1, true),
  (17, '🕐', 'Telling Time', '시간 말하기', 'قول الوقت', 'Tell time with Korean number systems.', 'قل الوقت بنظامَي الأرقام.', 'korean-1', 1, true),
  (18, '🎨', 'Colors', '색깔', 'الألوان', 'Color vocabulary and describing objects.', 'مفردات الألوان ووصف الأشياء.', 'korean-1', 1, true),
  (19, '👨‍👩‍👧‍👦', 'Family Members', '가족', 'أفراد العائلة', 'Family vocabulary with honorific titles.', 'مفردات العائلة مع الألقاب.', 'korean-1', 1, true),
  (20, '🍜', 'Food and Drinks', '음식과 음료', 'الطعام والشراب', 'Essential food vocabulary and ordering.', 'مفردات الطعام الأساسية والطلب.', 'korean-1', 1, true),
  (21, '🍽️', 'At the Restaurant', '식당에서', 'في المطعم', 'Order food and give feedback.', 'اطلب الطعام وأعطِ ملاحظات.', 'korean-1', 1, true),
  (22, '⏰', 'Daily Routines', '일과', 'الروتين اليومي', 'Morning to evening activities.', 'أنشطة من الصباح حتى المساء.', 'korean-1', 1, true),
  (23, '🌦️', 'Weather', '날씨', 'الطقس', 'Weather conditions and forecasts.', 'أحوال الطقس والتوقعات.', 'korean-1', 1, true),
  (24, '🌸', 'Seasons', '계절', 'الفصول', 'The four seasons and related activities.', 'الفصول الأربعة والأنشطة.', 'korean-1', 1, true),
  (25, '🫀', 'Body Parts', '신체 부위', 'أجزاء الجسم', 'Body parts for health contexts.', 'أجزاء الجسم في السياقات الصحية.', 'korean-1', 1, true),
  (26, '😊', 'Emotions', '감정', 'المشاعر', 'Express feelings and emotions.', 'عبِّر عن المشاعر والأحاسيس.', 'korean-1', 1, true),
  (27, '🎯', 'Hobbies', '취미', 'الهوايات', 'Talk about hobbies and free time.', 'تحدث عن الهوايات ووقت الفراغ.', 'korean-1', 1, true),
  (28, '🛒', 'Shopping', '쇼핑', 'التسوق', 'Shop and bargain at markets and malls.', 'تسوق وتفاوض.', 'korean-1', 1, true),
  (29, '🚌', 'Transportation', '교통수단', 'وسائل النقل', 'Use buses, subways, and taxis.', 'استخدم الحافلات والمترو وسيارات الأجرة.', 'korean-1', 1, true),
  (30, '🗺️', 'Directions', '길 안내', 'الاتجاهات', 'Ask for and give directions.', 'اسأل عن الاتجاهات وأعطها.', 'korean-1', 1, true),
  (31, '🏫', 'At School', '학교에서', 'في المدرسة', 'Classroom vocabulary and school life.', 'مفردات الفصل وحياة المدرسة.', 'korean-1', 1, true),
  (32, '💼', 'At Work', '직장에서', 'في العمل', 'Basic workplace vocabulary and phrases.', 'مفردات مكان العمل الأساسية.', 'korean-1', 1, true),
  (33, '🏥', 'At the Hospital', '병원에서', 'في المستشفى', 'Describe symptoms and talk to a doctor.', 'صف الأعراض وتحدث مع طبيب.', 'korean-1', 1, true),
  (34, '📱', 'Phone Calls', '전화 통화', 'المكالمات الهاتفية', 'Make and receive calls in Korean.', 'أجرِ واستقبل المكالمات.', 'korean-1', 1, true),
  (35, '🎉', 'Weekend Plans', '주말 계획', 'خطط عطلة نهاية الأسبوع', 'Make plans and suggestions.', 'ضع خططاً واقتراحات.', 'korean-1', 1, true),
  (36, '✈️', 'Travel and Tourism', '여행', 'السفر والسياحة', 'Plan trips and use travel vocabulary.', 'خطط للرحلات.', 'korean-1', 1, true),
  (37, '🏨', 'At the Hotel', '호텔에서', 'في الفندق', 'Check in and handle hotel situations.', 'تحقق من الدخول وتعامل مع مواقف الفندق.', 'korean-1', 1, true),
  (38, '🇰🇷', 'Korean Culture Basics', '한국 문화 기초', 'أساسيات الثقافة الكورية', 'Cultural customs, bowing, and etiquette.', 'الأعراف الثقافية والانحناء والآداب.', 'korean-1', 1, true),
  (39, '📌', 'Subject Particles 이/가 & 은/는', '주격 조사', 'جسيمات الفاعل', 'Use 이/가 and 은/는 correctly.', 'استخدم 이/가 و은/는 بشكل صحيح.', 'korean-1', 1, true),
  (40, '🎯', 'Object Particle 을/를', '목적격 조사', 'جسيمة المفعول', 'Mark direct objects with 을/를.', 'ميِّز المفاعيل بـ 을/를.', 'korean-1', 1, true),
  (41, '📍', 'Location Particles 에 & 에서', '장소 조사', 'جسيمات الموضع', 'Use 에 and 에서 correctly.', 'استخدم 에 و에서 بشكل صحيح.', 'korean-1', 1, true),
  (42, '⚖️', 'Topic vs Subject', '주제 vs 주격', 'الموضوع مقابل الفاعل', 'The difference between 은/는 and 이/가.', 'الفرق بين 은/는 و이/가.', 'korean-1', 1, true),
  (43, '📝', 'Verb Endings -아요/어요', '동사 어미', 'نهايات الأفعال', 'Present tense verb endings.', 'نهايات الأفعال في المضارع.', 'korean-1', 1, true),
  (44, '🌈', 'Descriptive Verbs', '형용사', 'الأفعال الوصفية', 'Use descriptive verbs as adjectives.', 'استخدم الأفعال الوصفية كصفات.', 'korean-1', 1, true),
  (45, '❌', 'Negation 안 & -지 않다', '부정 표현', 'النفي', 'Negate sentences with 안 and -지 않다.', 'انفِ الجمل بـ안 و-지 않다.', 'korean-1', 1, true),
  (46, '🔗', 'Connecting with -고', '-고 연결', 'الربط بـ -고', 'Connect actions sequentially with -고.', 'اربط الأفعال التتابعية بـ -고.', 'korean-1', 1, true),
  (47, '⏪', 'Past Tense -았/었어요', '과거 시제', 'الزمن الماضي', 'Form past tense naturally.', 'كوِّن الماضي بشكل طبيعي.', 'korean-1', 1, true),
  (48, '⏩', 'Future Tense -(으)ㄹ 거예요', '미래 시제', 'الزمن المستقبل', 'Express future plans.', 'عبِّر عن الخطط المستقبلية.', 'korean-1', 1, true),
  (49, '🙏', 'Polite Requests -아/어 주세요', '요청 표현', 'الطلبات المهذبة', 'Ask politely for help.', 'اطلب المساعدة بأدب.', 'korean-1', 1, true),
  (50, '💭', 'Expressing Opinions', '의견 말하기', 'إبداء الرأي', 'Share opinions in Korean.', 'شارك آراءك بالكورية.', 'korean-1', 1, true),
  (51, '❤️', 'Likes and Dislikes', '좋아하다/싫어하다', 'الإعجاب وعدمه', 'Express preferences.', 'عبِّر عن التفضيلات.', 'korean-1', 1, true),
  (52, '💪', 'Ability 할 수 있다/없다', '능력 표현', 'القدرة', 'Express ability and inability.', 'عبِّر عن القدرة وعدمها.', 'korean-1', 1, true),
  (53, '🚫', 'Permission and Prohibition', '허가와 금지', 'الإذن والنهي', 'Ask permission and prohibit actions.', 'اطلب الإذن وانهَ الأفعال.', 'korean-1', 1, true),
  (54, '⚖️', 'Comparisons -보다', '비교', 'المقارنة', 'Compare with -보다.', 'قارن بـ -보다.', 'korean-1', 1, true),
  (55, '🔊', 'Consonant Assimilation', '자음 동화', 'تماثل الحروف الساكنة', 'Nasalization and liquid assimilation.', 'التحنيف والسيولة.', 'korean-1', 1, true),
  (56, '🎩', 'Honorific Speech Intro', '존댓말 소개', 'مقدمة الكلام التبجيلي', 'Intro to -시- and formal speech.', 'مقدمة لـ -시- والكلام الرسمي.', 'korean-1', 1, true),
  (57, '📮', 'At the Post Office', '우체국에서', 'في مكتب البريد', 'Mail packages and letters.', 'أرسل الطرود والرسائل.', 'korean-1', 1, true),
  (58, '🏦', 'Banking', '은행에서', 'في البنك', 'Open accounts and bank transactions.', 'افتح حسابات وأجرِ معاملات.', 'korean-1', 1, true),
  (59, '📱', 'Smartphones and Apps', '스마트폰과 앱', 'الهواتف والتطبيقات', 'Digital Korean vocabulary.', 'مفردات الكورية الرقمية.', 'korean-1', 1, true),
  (60, '🎵', 'K-Pop and Hallyu', '케이팝과 한류', 'الكيبوب والهاليو', 'Korean pop culture vocabulary.', 'مفردات الثقافة الكورية الشعبية.', 'korean-1', 1, true),
  (61, '📄', 'TOPIK 1 Reading 1', '토픽 1 읽기 1', 'قراءة TOPIK 1 - ١', 'Practice short informational texts.', 'تمرن على النصوص المعلوماتية القصيرة.', 'korean-1', 1, true),
  (62, '🪧', 'TOPIK 1 Reading 2', '토픽 1 읽기 2', 'قراءة TOPIK 1 - ٢', 'Read advertisements and signs.', 'اقرأ الإعلانات واللافتات.', 'korean-1', 1, true),
  (63, '🎧', 'TOPIK 1 Listening 1', '토픽 1 듣기 1', 'استماع TOPIK 1 - ١', 'Short conversation dialogues.', 'حوارات المحادثة القصيرة.', 'korean-1', 1, true),
  (64, '📢', 'TOPIK 1 Listening 2', '토픽 1 듣기 2', 'استماع TOPIK 1 - ٢', 'Announcements and instructions.', 'الإعلانات والتعليمات.', 'korean-1', 1, true),
  (65, '📋', 'TOPIK 1 Vocabulary Review', '토픽 1 어휘 복습', 'مراجعة مفردات TOPIK 1', 'Key vocabulary from TOPIK 1.', 'المفردات الرئيسية من TOPIK 1.', 'korean-1', 1, true),
  (66, '📝', 'TOPIK 1 Grammar Review', '토픽 1 문법 복습', 'مراجعة قواعد TOPIK 1', 'Essential grammar for TOPIK 1.', 'القواعد الأساسية لـ TOPIK 1.', 'korean-1', 1, true),
  (67, '🏫', 'Classroom Language', '교실 표현', 'لغة الفصل الدراسي', 'Instructions used in the classroom.', 'التعليمات المستخدمة في الفصل.', 'korean-1', 1, true),
  (68, '🌿', 'Nature and Environment', '자연과 환경', 'الطبيعة والبيئة', 'Nature, plants, and animal vocabulary.', 'مفردات الطبيعة والنباتات والحيوانات.', 'korean-1', 1, true),
  (69, '👤', 'Physical Appearance', '외모 묘사', 'المظهر الجسدي', 'Describe people''s physical appearance.', 'صف المظهر الجسدي للناس.', 'korean-1', 1, true),
  (70, '🌟', 'Personality Traits', '성격', 'سمات الشخصية', 'Describe character and personality.', 'صف الطابع والشخصية.', 'korean-1', 1, true),
  (71, '🎊', 'Celebrations and Holidays', '명절과 공휴일', 'الاحتفالات والعطل', 'Korean holiday vocabulary.', 'مفردات العطل الكورية.', 'korean-1', 1, true),
  (72, '⚽', 'Sports and Exercise', '스포츠와 운동', 'الرياضة والتمارين', 'Sports and physical activity vocabulary.', 'مفردات الرياضة والأنشطة البدنية.', 'korean-1', 1, true),
  (73, '📝', 'TOPIK 1 Mock Test 1', '토픽 1 모의고사 1', 'اختبار TOPIK 1 التجريبي ١', 'Full practice test for TOPIK 1.', 'اختبار تدريبي كامل لـ TOPIK 1.', 'korean-1', 1, true),
  (74, '📝', 'TOPIK 1 Mock Test 2', '토픽 1 모의고사 2', 'اختبار TOPIK 1 التجريبي ٢', 'Second practice test for TOPIK 1.', 'الاختبار التدريبي الثاني.', 'korean-1', 1, true),
  (75, '🏆', 'TOPIK 1 Final Review', '토픽 1 총복습', 'المراجعة النهائية TOPIK 1', 'Complete review of all TOPIK 1 content.', 'مراجعة كاملة لمحتوى TOPIK 1.', 'korean-1', 1, true),
  (76, '🔗', 'Complex Sentences', '복문', 'الجمل المركبة', 'Build complex sentences with multiple clauses.', 'بناء جمل معقدة بجمل فرعية متعددة.', 'korean-1', 2, true),
  (77, '🎩', 'Formal Speech Endings', '격식체', 'الكلام الرسمي', 'Use -ㅂ니다/습니다 in formal contexts.', 'استخدم -ㅂ니다/습니다 في السياقات الرسمية.', 'korean-1', 2, true),
  (78, '📜', 'Written vs Spoken Korean', '문어체 vs 구어체', 'الكتابي مقابل المنطوق', 'Differences between written and spoken language.', 'الفروق بين اللغتين المكتوبة والمنطوقة.', 'korean-1', 2, true),
  (79, '🔍', 'Advanced Particles', '고급 조사', 'الجسيمات المتقدمة', '에게, 한테, 께 and other advanced particles.', '에게 وها한테 وغيرها.', 'korean-1', 2, true),
  (80, '⛓️', 'Clause Connectors', '절 접속사', 'روابط الجمل', 'Connect clauses with -아서/어서, -(으)면서.', 'اربط بـ -아서/어서 و-(으)면서.', 'korean-1', 2, true),
  (81, '🔀', 'Conditional Sentences', '조건문', 'الجمل الشرطية', 'Form conditionals with -(으)면 and -아/어야.', 'كوِّن الشرطيات.', 'korean-1', 2, true),
  (82, '🔄', 'Passive Voice', '피동 표현', 'المبني للمجهول', 'Passive verbs with -이/히/리/기-.', 'أفعال مبنية للمجهول.', 'korean-1', 2, true),
  (83, '🎭', 'Causative Verbs', '사동 표현', 'أفعال التسبب', 'Make someone do something.', 'اجعل شخصاً يفعل شيئاً.', 'korean-1', 2, true),
  (84, '💬', 'Reported Speech', '간접 화법', 'الكلام المنقول', 'Report what others said or thought.', 'أبلغ عما قاله الآخرون.', 'korean-1', 2, true),
  (85, '🏯', 'Korean History', '한국 역사', 'التاريخ الكوري', 'Key periods in Korean history.', 'الفترات الرئيسية في التاريخ الكوري.', 'korean-1', 2, true),
  (86, '🎎', 'Traditional Culture', '한국 전통 문화', 'الثقافة التقليدية', 'Arts, clothing, and traditional customs.', 'الفنون والملابس والأعراف التقليدية.', 'korean-1', 2, true),
  (87, '🏙️', 'Modern Society', '현대 한국 사회', 'المجتمع الحديث', 'Education, work culture, and social norms.', 'التعليم وثقافة العمل والأعراف الاجتماعية.', 'korean-1', 2, true),
  (88, '📺', 'Media and Entertainment', '미디어와 엔터테인먼트', 'الإعلام والترفيه', 'News, TV, and online media discussion.', 'أخبار والتلفزيون والإعلام الإلكتروني.', 'korean-1', 2, true),
  (89, '🥘', 'Korean Food Culture', '한국 음식 문화', 'ثقافة الطعام الكوري', 'Deep dive into Korean culinary traditions.', 'تعمق في التقاليد الطهوية الكورية.', 'korean-1', 2, true),
  (90, '💭', 'Opinion Expressions', '의견 표현', 'تعبيرات الرأي', 'Express and argue opinions formally.', 'عبِّر عن الآراء وناقشها رسمياً.', 'korean-1', 2, true),
  (91, '📰', 'News Reading 1', '뉴스 읽기 1', 'قراءة الأخبار ١', 'Analyze news headlines and articles.', 'حلِّل العناوين الإخبارية والمقالات.', 'korean-1', 2, true),
  (92, '📡', 'News Reading 2', '뉴스 읽기 2', 'قراءة الأخبار ٢', 'Formal news language and vocabulary.', 'لغة الأخبار الرسمية.', 'korean-1', 2, true),
  (93, '📝', 'Essay Structure', '글쓰기 구조', 'هيكل المقال', 'Intro, body, and conclusion organization.', 'تنظيم المقدمة والجسم والخاتمة.', 'korean-1', 2, true),
  (94, '📈', 'Describing Trends', '경향 묘사', 'وصف الاتجاهات', 'Describe social trends and statistics.', 'صف الاتجاهات الاجتماعية.', 'korean-1', 2, true),
  (95, '🔧', 'Problem and Solution', '문제와 해결', 'المشكلة والحل', 'Discuss problems and propose solutions.', 'ناقش المشكلات واقترح الحلول.', 'korean-1', 2, true),
  (96, '⚖️', 'Comparison and Contrast', '비교와 대조', 'المقارنة والمقابلة', 'Compare two ideas, periods, or places.', 'قارن فكرتين أو حقبتين.', 'korean-1', 2, true),
  (97, '📋', 'Formal Writing', '공식적 글쓰기', 'الكتابة الرسمية', 'Formal letters, reports, and notices.', 'رسائل وتقارير وإشعارات رسمية.', 'korean-1', 2, true),
  (98, '👀', 'Evidential Markers', '증거 표현', 'علامات الإثبات', 'Use -더라, -네, -군요 for observations.', 'استخدم -더라 و-네 و-군요.', 'korean-1', 2, true),
  (99, '👑', 'Advanced Honorifics', '고급 존댓말', 'الحرمة المتقدمة', 'Master the full honorific system.', 'أتقن نظام الحرمة الكاملة.', 'korean-1', 2, true),
  (100, '🌀', 'Subjunctive Patterns', '가정 표현', 'الأنماط الافتراضية', 'Express hypothetical situations.', 'عبِّر عن المواقف الافتراضية.', 'korean-1', 2, true),
  (101, '❗', 'Emphatic Patterns', '강조 표현', 'أنماط التأكيد', 'Add emphasis with -기는 하다.', 'أضف تأكيداً.', 'korean-1', 2, true),
  (102, '🤝', 'Concessive Expressions', '양보 표현', 'تعبيرات التنازل', 'Use -아도/어도 and -더라도.', 'استخدم -아도/어도 و-더라도.', 'korean-1', 2, true),
  (103, '📢', 'Indirect Commands', '간접 명령', 'الأوامر غير المباشرة', 'Report commands of others.', 'أبلغ عن أوامر الآخرين.', 'korean-1', 2, true),
  (104, '🗣️', 'Regional Dialects', '한국 방언', 'اللهجات الإقليمية', 'Busan, Jeju, and other Korean dialects.', 'لهجات بوسان وجيجو وغيرها.', 'korean-1', 2, true),
  (105, '📖', 'Advanced Reading 1', '고급 읽기 1', 'القراءة المتقدمة ١', 'Comprehend complex expository texts.', 'افهم النصوص الوصفية المعقدة.', 'korean-1', 2, true),
  (106, '📚', 'Advanced Reading 2', '고급 읽기 2', 'القراءة المتقدمة ٢', 'Analyze argumentative texts.', 'حلِّل النصوص الجدلية.', 'korean-1', 2, true),
  (107, '✍️', 'TOPIK 2 Writing Practice', '토픽 2 작문 연습', 'تمرين كتابة TOPIK 2', 'Practice the TOPIK 2 writing section.', 'تمرن على كتابة TOPIK 2.', 'korean-1', 2, true),
  (108, '🧩', 'Advanced Grammar 1', '고급 문법 1', 'القواعد المتقدمة ١', 'Patterns: -(으)ㄹ 텐데, -는 바람에.', 'أنماط متقدمة.', 'korean-1', 2, true),
  (109, '🔬', 'Advanced Grammar 2', '고급 문법 2', 'القواعد المتقدمة ٢', 'Patterns: -(으)ㄹ 뿐만 아니라.', 'أنماط متقدمة.', 'korean-1', 2, true),
  (110, '🔭', 'Advanced Grammar 3', '고급 문법 3', 'القواعد المتقدمة ٣', 'Patterns: -에 불과하다.', 'أنماط متقدمة.', 'korean-1', 2, true),
  (111, '📐', 'Advanced Grammar 4', '고급 문법 4', 'القواعد المتقدمة ٤', 'Patterns: -(으)로 인해, -에 따르면.', 'أنماط متقدمة.', 'korean-1', 2, true),
  (112, '🎯', 'Advanced Grammar 5', '고급 문법 5', 'القواعد المتقدمة ٥', 'Patterns: -에도 불구하고.', 'أنماط متقدمة.', 'korean-1', 2, true),
  (113, '📄', 'TOPIK 2 Reading Practice', '토픽 2 읽기 연습', 'تمرين قراءة TOPIK 2', 'TOPIK 2 reading comprehension.', 'فهم القراءة في TOPIK 2.', 'korean-1', 2, true),
  (114, '🎧', 'TOPIK 2 Listening Practice', '토픽 2 듣기 연습', 'تمرين استماع TOPIK 2', 'TOPIK 2 listening section.', 'قسم الاستماع في TOPIK 2.', 'korean-1', 2, true),
  (115, '📋', 'TOPIK 2 Grammar Review', '토픽 2 문법 총정리', 'مراجعة قواعد TOPIK 2', 'Complete grammar review for TOPIK 2.', 'مراجعة القواعد لـ TOPIK 2.', 'korean-1', 2, true),
  (116, '📝', 'TOPIK 2 Mock Test 1', '토픽 2 모의고사 1', 'اختبار TOPIK 2 - ١', 'TOPIK 2 reading simulation.', 'محاكاة قراءة TOPIK 2.', 'korean-1', 2, true),
  (117, '📝', 'TOPIK 2 Mock Test 2', '토픽 2 모의고사 2', 'اختبار TOPIK 2 - ٢', 'TOPIK 2 listening simulation.', 'محاكاة استماع TOPIK 2.', 'korean-1', 2, true),
  (118, '📝', 'TOPIK 2 Mock Test 3', '토픽 2 모의고사 3', 'اختبار TOPIK 2 - ٣', 'TOPIK 2 writing simulation.', 'محاكاة كتابة TOPIK 2.', 'korean-1', 2, true),
  (119, '🏆', 'TOPIK 2 Final Review', '토픽 2 총복습', 'المراجعة النهائية TOPIK 2', 'Complete TOPIK 2 content review.', 'مراجعة كاملة لـ TOPIK 2.', 'korean-1', 2, true),
  (120, '🌉', 'Bridge to Intermediate High', '중고급 교량', 'جسر للمستوى العالي', 'Transition from TOPIK 2 to TOPIK 3.', 'انتقال من TOPIK 2 إلى TOPIK 3.', 'korean-1', 2, true),
  (121, '🌍', 'Real-Life Complex Topics', '실생활 복잡한 주제', 'مواضيع الحياة الواقعية', 'Discuss complex everyday topics fluently.', 'ناقش مواضيع الحياة المعقدة بطلاقة.', 'korean-1', 3, true),
  (122, '🎙️', 'Debates and Argumentation', '토론과 논증', 'النقاش والحجج', 'Structure and present arguments.', 'هيكل الحجج وقدِّمها.', 'korean-1', 3, true),
  (123, '🎚️', 'Formal vs Informal Registers', '격식 vs 비격식', 'الرسمي مقابل غير الرسمي', 'Switch between speech levels.', 'انتقل بين مستويات الكلام.', 'korean-1', 3, true),
  (124, '📖', 'Literary Reading Intro', '문학 읽기 입문', 'مقدمة القراءة الأدبية', 'Read simple Korean literary texts.', 'اقرأ النصوص الأدبية الكورية البسيطة.', 'korean-1', 3, true),
  (125, '🏘️', 'Korean Social Issues', '한국 사회 문제', 'القضايا الاجتماعية', 'Education, housing, and job market issues.', 'قضايا التعليم والإسكان وسوق العمل.', 'korean-1', 3, true),
  (126, '🌱', 'Environmental Topics', '환경 주제', 'الموضوعات البيئية', 'Climate change and sustainability.', 'تغير المناخ والاستدامة.', 'korean-1', 3, true),
  (127, '🌏', 'Cultural Comparison', '문화 비교', 'المقارنة الثقافية', 'Compare Korean with other cultures.', 'قارن الثقافة الكورية بالثقافات الأخرى.', 'korean-1', 3, true),
  (128, '📧', 'Business Correspondence', '비즈니스 서신', 'المراسلات التجارية', 'Professional emails and formal letters.', 'رسائل بريد إلكتروني احترافية.', 'korean-1', 3, true),
  (129, '🎧', 'Advanced Listening 1', '고급 듣기 1', 'الاستماع المتقدم ١', 'Understand lectures and presentations.', 'افهم المحاضرات والعروض.', 'korean-1', 3, true),
  (130, '📻', 'Advanced Listening 2', '고급 듣기 2', 'الاستماع المتقدم ٢', 'Follow debates and discussions.', 'تابع النقاشات والحوارات.', 'korean-1', 3, true),
  (131, '📊', 'Social Issues Vocabulary', '사회 어휘', 'مفردات القضايا الاجتماعية', 'Social, political, and economic terms.', 'مصطلحات اجتماعية وسياسية واقتصادية.', 'korean-1', 3, true),
  (132, '🩺', 'Health and Medicine', '건강과 의학', 'الصحة والطب', 'Medical vocabulary and healthcare.', 'المفردات الطبية والرعاية الصحية.', 'korean-1', 3, true),
  (133, '💻', 'Technology and Innovation', '기술과 혁신', 'التكنولوجيا والابتكار', 'Tech trends and digital transformation.', 'اتجاهات التكنولوجيا والتحول الرقمي.', 'korean-1', 3, true),
  (134, '📄', 'TOPIK 3 Reading Practice', '토픽 3 읽기 연습', 'تمرين قراءة TOPIK 3', 'B1-level reading comprehension.', 'فهم القراءة على مستوى B1.', 'korean-1', 3, true),
  (135, '✅', 'TOPIK 3 Checkpoint', '토픽 3 체크포인트', 'نقطة تفتيش TOPIK 3', 'Assessment of all TOPIK 3 skills.', 'تقييم مهارات TOPIK 3.', 'korean-1', 3, true),
  (136, '⚖️', 'Legal and Government', '법률과 정부', 'القانون والحكومة', 'Law, courts, and governance vocabulary.', 'مفردات القانون والمحاكم والحوكمة.', 'korean-1', 3, true),
  (137, '💹', 'Economy and Finance', '경제와 금융', 'الاقتصاد والمالية', 'Economic concepts and financial news.', 'المفاهيم الاقتصادية والأخبار المالية.', 'korean-1', 3, true),
  (138, '🎓', 'Education System', '교육 제도', 'نظام التعليم', 'Korean education structure and academic language.', 'هيكل التعليم الكوري ولغة الأكاديميا.', 'korean-1', 3, true),
  (139, '🏛️', 'Politics and Society', '정치와 사회', 'السياسة والمجتمع', 'Political vocabulary and civic discussion.', 'المفردات السياسية والنقاش المدني.', 'korean-1', 3, true),
  (140, '🌟', 'TOPIK 3 Full Review', '토픽 3 총복습', 'المراجعة الكاملة TOPIK 3', 'Comprehensive review of B1 content.', 'مراجعة شاملة لمحتوى B1.', 'korean-1', 3, true),
  (141, '💼', 'Professional Introductions', '전문적 자기소개', 'التعريف المهني', 'Introduce yourself in business settings.', 'قدم نفسك في بيئات الأعمال.', 'korean-1', 4, true),
  (142, '📊', 'Meetings and Presentations', '회의와 발표', 'الاجتماعات والعروض', 'Lead meetings and presentations.', 'قُد الاجتماعات وقدم عروضاً.', 'korean-1', 4, true),
  (143, '🤝', 'Negotiation Language', '협상 표현', 'لغة التفاوض', 'Negotiate deals professionally.', 'تفاوض على الصفقات باحترافية.', 'korean-1', 4, true),
  (144, '💎', 'Advanced Idioms 1', '고급 관용구 1', 'الاصطلاحات المتقدمة ١', 'Common Korean idioms in context.', 'الاصطلاحات الكورية الشائعة في السياق.', 'korean-1', 4, true),
  (145, '📜', 'Advanced Idioms 2', '고급 관용구 2', 'الاصطلاحات المتقدمة ٢', 'Four-character idioms (사자성어).', 'الاصطلاحات الرباعية الحروف.', 'korean-1', 4, true),
  (146, '🔬', 'Academic Language 1', '학문적 언어 1', 'اللغة الأكاديمية ١', 'Vocabulary for academic writing.', 'المفردات للكتابة الأكاديمية.', 'korean-1', 4, true),
  (147, '🔭', 'Academic Language 2', '학문적 언어 2', 'اللغة الأكاديمية ٢', 'Citation, argumentation, analysis.', 'الاقتباس والحجاج والتحليل.', 'korean-1', 4, true),
  (148, '🏢', 'Korean Corporate Culture', '한국 기업 문화', 'الثقافة المؤسسية الكورية', 'Hierarchy, office norms, and etiquette.', 'التسلسل الهرمي وأعراف المكتب.', 'korean-1', 4, true),
  (149, '🎭', 'Nuanced Expressions', '미묘한 표현', 'التعبيرات الدقيقة', 'Subtle meaning differences in usage.', 'الاختلافات الدقيقة في المعنى.', 'korean-1', 4, true),
  (150, '📖', 'TOPIK 4 Reading Practice', '토픽 4 읽기 연습', 'تمرين قراءة TOPIK 4', 'B2-level reading comprehension.', 'فهم القراءة على مستوى B2.', 'korean-1', 4, true),
  (151, '📋', 'Formal Writing 2', '공식적 글쓰기 2', 'الكتابة الرسمية ٢', 'Reports, proposals, and documents.', 'التقارير والمقترحات والوثائق.', 'korean-1', 4, true),
  (152, '🧠', 'Critical Thinking in Korean', '한국어 비판적 사고', 'التفكير النقدي بالكورية', 'Analyze and evaluate arguments.', 'حلِّل الحجج وقيِّمها.', 'korean-1', 4, true),
  (153, '🗳️', 'Korean Politics Deep Dive', '한국 정치 심층 분석', 'السياسة الكورية المتعمقة', 'Government structure and policy.', 'هيكل الحكومة والسياسة.', 'korean-1', 4, true),
  (154, '📰', 'Social Commentary', '사회 논평', 'التعليق الاجتماعي', 'Write and deliver social commentary.', 'اكتب التعليق الاجتماعي وقدِّمه.', 'korean-1', 4, true),
  (155, '🔩', 'Advanced Grammar Patterns 1', '고급 문법 패턴 1', 'أنماط القواعد المتقدمة ١', 'Complex patterns for B2 level.', 'أنماط معقدة لمستوى B2.', 'korean-1', 4, true),
  (156, '⚙️', 'Advanced Grammar Patterns 2', '고급 문법 패턴 2', 'أنماط القواعد المتقدمة ٢', 'Advanced connectors and modals.', 'روابط وتعبيرات أسلوبية متقدمة.', 'korean-1', 4, true),
  (157, '📝', 'TOPIK 4 Mock Test', '토픽 4 모의고사', 'اختبار TOPIK 4 التجريبي', 'Full TOPIK 4 simulation.', 'محاكاة كاملة لـ TOPIK 4.', 'korean-1', 4, true),
  (158, '✅', 'TOPIK 4 Checkpoint', '토픽 4 체크포인트', 'نقطة تفتيش TOPIK 4', 'Assessment of upper-intermediate skills.', 'تقييم مهارات المستوى المتوسط العلوي.', 'korean-1', 4, true),
  (159, '✍️', 'Academic Writing Structure', '학술적 글쓰기 구조', 'هيكل الكتابة الأكاديمية', 'Thesis, arguments, and conclusions.', 'الأطروحة والحجج والاستنتاجات.', 'korean-1', 5, true),
  (160, '🌌', 'Abstract Vocabulary', '추상적 어휘', 'المفردات المجردة', 'Words for thought and abstract concepts.', 'كلمات الفكر والمفاهيم المجردة.', 'korean-1', 5, true),
  (161, '📚', 'Literary Analysis', '문학 분석', 'التحليل الأدبي', 'Analyze themes and style in Korean literature.', 'حلِّل الموضوعات والأسلوب في الأدب الكوري.', 'korean-1', 5, true),
  (162, '🎨', 'Rhetorical Devices', '수사 기법', 'الأساليب البلاغية', 'Metaphor, simile, irony, and parallelism.', 'الاستعارة والتشبيه والسخرية والتوازي.', 'korean-1', 5, true),
  (163, '📜', 'Classical Grammar Patterns', '고전 문법 패턴', 'أنماط القواعد الكلاسيكية', 'Literary endings and classical structures.', 'النهايات الأدبية والتراكيب الكلاسيكية.', 'korean-1', 5, true),
  (164, '🔬', 'Research Language', '연구 언어', 'لغة البحث', 'Methodology and academic research vocab.', 'مفردات المنهجية والبحث الأكاديمي.', 'korean-1', 5, true),
  (165, '👑', 'Advanced Honorific Mastery', '존댓말 완전 정복', 'إتقان الحرمة المتقدمة', 'Full mastery of speech level hierarchy.', 'الإتقان الكامل للتسلسل الهرمي.', 'korean-1', 5, true),
  (166, '🎤', 'Professional Presentations', '전문적 발표', 'مهارات العرض المهني', 'Advanced presentation and persuasion.', 'هياكل العرض المتقدمة والإقناع.', 'korean-1', 5, true),
  (167, '🌸', 'Cultural Subtext', '문화적 함의', 'السياق الثقافي الضمني', 'Implicit meanings and indirect communication.', 'المعاني الضمنية والتواصل غير المباشر.', 'korean-1', 5, true),
  (168, '📖', 'Advanced Reading — Essays', '고급 독해 — 수필', 'القراءة المتقدمة — المقالات', 'Read classical and modern Korean essays.', 'اقرأ المقالات الكورية.', 'korean-1', 5, true),
  (169, '📕', 'Advanced Reading — Fiction', '고급 독해 — 소설', 'القراءة المتقدمة — الروايات', 'Analyze Korean novel extracts.', 'حلِّل مقاطع الروايات الكورية.', 'korean-1', 5, true),
  (170, '🏆', 'TOPIK 5 Writing Mastery', '토픽 5 작문 마스터', 'إتقان كتابة TOPIK 5', 'High-scoring essays for TOPIK 5.', 'مقالات عالية الدرجات لـ TOPIK 5.', 'korean-1', 5, true),
  (171, '📄', 'TOPIK 5 Reading Practice', '토픽 5 읽기 연습', 'تمرين قراءة TOPIK 5', 'C1-level reading comprehension.', 'فهم القراءة على مستوى C1.', 'korean-1', 5, true),
  (172, '✅', 'TOPIK 5 Checkpoint', '토픽 5 체크포인트', 'نقطة تفتيش TOPIK 5', 'Comprehensive C1 proficiency assessment.', 'تقييم شامل لمستوى C1.', 'korean-1', 5, true),
  (173, '🌟', 'Near-Native Fluency', '원어민 수준 유창성', 'الطلاقة شبه الأصلية', 'Natural speech patterns and native-like expressions.', 'أنماط الكلام الطبيعية والتعبيرات شبه الأصلية.', 'korean-1', 6, true),
  (174, '📜', 'Classical Korean', '문어체 한국어', 'الكورية الكلاسيكية', 'Classical literary style and archaic grammar.', 'الأسلوب الأدبي الكلاسيكي والقواعد العتيقة.', 'korean-1', 6, true),
  (175, '🗣️', 'Regional Dialect Mastery', '방언 완전 이해', 'إتقان اللهجات الإقليمية', 'Understand major Korean dialects.', 'فهم اللهجات الكورية الرئيسية.', 'korean-1', 6, true),
  (176, '📺', 'Broadcasting Korean', '방송 한국어', 'الكورية في الإعلام', 'Broadcast language, anchoring, narration.', 'لغة البث والتقديم والسرد.', 'korean-1', 6, true),
  (177, '💎', 'Idiomatic Mastery', '관용구 완전 정복', 'إتقان الاصطلاحات', 'Proverbs, idioms, and neologisms.', 'الأمثال والاصطلاحات والكلمات الجديدة.', 'korean-1', 6, true),
  (178, '🔄', 'Translation Principles', '번역과 통역', 'مبادئ الترجمة', 'Korean-English translation principles.', 'مبادئ الترجمة بين الكورية والإنجليزية.', 'korean-1', 6, true),
  (179, '📝', 'TOPIK 6 Mock Exam', '토픽 6 모의고사', 'امتحان TOPIK 6 التجريبي', 'Full TOPIK 6 simulation.', 'محاكاة كاملة لـ TOPIK 6.', 'korean-1', 6, true),
  (180, '🏅', 'TOPIK 6 Mastery', '토픽 6 마스터리', 'إتقان TOPIK 6', 'Final comprehensive assessment.', 'التقييم الشامل النهائي.', 'korean-1', 6, true),
  (1, '⏰', 'Waking Up', '잠 깨기', 'الاستيقاظ', 'Vocabulary for waking up and getting out of bed.', 'مفردات الاستيقاظ والنهوض.', 'daily-routine', 1, true),
  (2, '🪥', 'Morning Hygiene', '아침 위생', 'النظافة الصباحية', 'Brushing teeth, washing face, and showering.', 'تنظيف الأسنان وغسيل الوجه.', 'daily-routine', 1, true),
  (3, '👔', 'Getting Dressed', '옷 입기', 'ارتداء الملابس', 'Clothing vocabulary and outfits.', 'مفردات الملابس والأزياء.', 'daily-routine', 1, true),
  (4, '🍳', 'Breakfast', '아침 식사', 'وجبة الإفطار', 'Breakfast foods and morning drinks.', 'أطعمة الإفطار والمشروبات.', 'daily-routine', 1, true),
  (5, '🚇', 'Commuting', '통근', 'التنقل للعمل', 'Bus, subway, and commute vocabulary.', 'مفردات الحافلة والمترو والتنقل.', 'daily-routine', 1, true),
  (6, '🏢', 'Arriving at Work/School', '직장·학교 도착', 'الوصول للعمل/المدرسة', 'Greetings and arrival phrases.', 'تحيات وعبارات الوصول.', 'daily-routine', 1, true),
  (7, '🌅', 'Morning Routine Summary', '오전 일과 정리', 'ملخص الروتين الصباحي', 'Describe full morning from wake-up.', 'صف صباحك الكامل.', 'daily-routine', 1, true),
  (8, '☕', 'Coffee and Tea Culture', '커피·차 문화', 'ثقافة القهوة والشاي', 'Order and discuss hot beverages.', 'اطلب المشروبات الساخنة وناقشها.', 'daily-routine', 1, true),
  (9, '📋', 'Planning Your Day', '하루 계획 세우기', 'تخطيط يومك', 'To-do lists and schedule vocabulary.', 'قوائم المهام ومفردات الجدول الزمني.', 'daily-routine', 1, true),
  (10, '🌤️', 'Morning Expressions', '아침 표현', 'تعبيرات الصباح', 'Greetings specific to mornings.', 'تحيات خاصة بالصباح.', 'daily-routine', 1, true),
  (11, '🍲', 'Cooking Dinner', '저녁 요리', 'طبخ العشاء', 'Recipe vocabulary and cooking verbs.', 'مفردات الوصفات وأفعال الطبخ.', 'daily-routine', 1, true),
  (12, '🧹', 'Household Chores', '집안일', 'أعمال المنزل', 'Cleaning, organizing, and maintaining.', 'التنظيف والتنظيم والصيانة.', 'daily-routine', 1, true),
  (13, '🛍️', 'Grocery Shopping', '식료품 쇼핑', 'التسوق للبقالة', 'Buy groceries and navigate the supermarket.', 'اشترِ البقالة وتنقل في السوق.', 'daily-routine', 1, true),
  (14, '🧺', 'Laundry', '빨래', 'الغسيل', 'Washing, drying, and folding clothes.', 'غسيل وتجفيف وطي الملابس.', 'daily-routine', 1, true),
  (15, '🔧', 'Home Repairs', '집 수리', 'إصلاح المنزل', 'Basic home repair vocabulary.', 'مفردات إصلاح المنزل الأساسية.', 'daily-routine', 1, true),
  (16, '👨‍👩‍👧', 'Family Time at Home', '가족과 집에서의 시간', 'وقت العائلة', 'Activities and conversations with family.', 'الأنشطة والمحادثات مع العائلة.', 'daily-routine', 1, true),
  (17, '📱', 'Using a Smartphone', '스마트폰 사용', 'استخدام الهاتف الذكي', 'Apps, calls, texts vocabulary.', 'التطبيقات والمكالمات والرسائل.', 'daily-routine', 1, true),
  (18, '📺', 'Watching TV', 'TV 시청', 'مشاهدة التلفزيون', 'Shows, channels, and TV habits.', 'البرامج والقنوات وعادات التلفزيون.', 'daily-routine', 1, true),
  (19, '📲', 'Social Media', '소셜 미디어', 'التواصل الاجتماعي', 'Korean social media vocabulary.', 'مفردات التواصل الاجتماعي الكورية.', 'daily-routine', 1, true),
  (20, '📖', 'Reading and Studying', '독서와 공부', 'القراءة والدراسة', 'Study habits and reading vocabulary.', 'عادات الدراسة ومفردات القراءة.', 'daily-routine', 1, true),
  (21, '🛒', 'Online Shopping', '온라인 쇼핑', 'التسوق عبر الإنترنت', 'Order products online and track delivery.', 'اطلب المنتجات إلكترونياً.', 'daily-routine', 2, true),
  (22, '🏃', 'Body and Movement', '몸과 움직임', 'الجسم والحركة', 'Body part verbs and movement.', 'أفعال أجزاء الجسم والحركة.', 'daily-routine', 1, true),
  (23, '👁️', 'The Five Senses', '감각', 'الحواس الخمس', 'Sight, hearing, smell, taste, touch.', 'البصر والسمع والشم والتذوق واللمس.', 'daily-routine', 1, true),
  (24, '🤕', 'Pain and Discomfort', '통증과 불편함', 'الألم والانزعاج', 'Describe physical discomfort and symptoms.', 'صف الانزعاج الجسدي والأعراض.', 'daily-routine', 1, true),
  (25, '🏋️', 'Exercise and Fitness', '운동과 피트니스', 'الرياضة واللياقة', 'Gym, sports, and fitness vocabulary.', 'مفردات الجيم والرياضة.', 'daily-routine', 1, true),
  (26, '😴', 'Sleep and Rest', '수면과 휴식', 'النوم والراحة', 'Sleeping habits and rest vocabulary.', 'عادات النوم ومفردات الراحة.', 'daily-routine', 1, true),
  (27, '⚡', 'Energy and Fatigue', '피곤함과 활력', 'الطاقة والتعب', 'Express energy levels and fatigue.', 'عبِّر عن مستويات الطاقة.', 'daily-routine', 1, true),
  (28, '🩺', 'Medical Appointment', '병원 예약', 'موعد طبي', 'Make appointments and talk to a doctor.', 'حدد مواعيد وتحدث مع طبيب.', 'daily-routine', 1, true),
  (29, '❤️', 'Body and Health Review', '몸과 건강 복습', 'مراجعة الجسم والصحة', 'Review body vocabulary in health contexts.', 'راجع مفردات الجسم الصحية.', 'daily-routine', 2, true),
  (30, '🎂', 'Birthdays and Anniversaries', '생일과 기념일', 'الأعياد والذكريات', 'Celebrate and give wishes.', 'احتفل وأرسل التمنيات.', 'daily-routine', 1, true),
  (31, '💐', 'Weddings and Funerals', '결혼식과 장례식', 'الأعراس والجنازات', 'Formal events and condolences.', 'المناسبات الرسمية والتعازي.', 'daily-routine', 2, true),
  (32, '🎊', 'Year-End Traditions', '연말 전통', 'تقاليد نهاية العام', 'New Year, Seollal, and Chuseok.', 'احتفالات رأس السنة وسيولال وتشوسيوك.', 'daily-routine', 2, true),
  (1, '👋', 'First Encounter', '첫 만남', 'اللقاء الأول', 'Greetings and first impressions from K-Dramas.', 'التحيات والانطباعات الأولى.', 'kdrama', 1, true),
  (2, '📱', 'Exchanging Contacts', '연락처 교환', 'تبادل جهات الاتصال', 'Ask for numbers and social handles.', 'اطلب الأرقام ومعرفات التواصل.', 'kdrama', 1, true),
  (3, '☕', 'Small Talk', '가벼운 대화', 'الحديث العابر', 'Casual conversation starters.', 'مواضيع محادثة عابرة.', 'kdrama', 1, true),
  (4, '✨', 'Memorable Introductions', '인상적인 자기소개', 'التعريف اللافت', 'Dramatic self-introductions K-Drama style.', 'التعريف بالنفس بأسلوب الدراما.', 'kdrama', 1, true),
  (5, '😅', 'Awkward Meetings', '어색한 만남', 'اللقاءات المحرجة', 'First-meeting tension and awkwardness.', 'توتر وإحراج اللقاء الأول.', 'kdrama', 1, true),
  (6, '💕', 'Love Confession', '사랑 고백', 'الاعتراف بالحب', 'Classic K-Drama love confessions.', 'اعترافات الحب الكلاسيكية.', 'kdrama', 1, true),
  (7, '🌹', 'Dating Expressions', '데이트 표현', 'تعبيرات المواعدة', 'Ask someone out and plan dates.', 'اطلب موعداً وخطط له.', 'kdrama', 1, true),
  (8, '😤', 'Jealousy Scenes', '질투 장면', 'مشاهد الغيرة', 'Dramatic jealousy from romcoms.', 'تعبيرات الغيرة الدرامية.', 'kdrama', 1, true),
  (9, '🤝', 'Making Up', '화해', 'المصالحة', 'Apologies and reconciliation.', 'الاعتذار والمصالحة.', 'kdrama', 1, true),
  (10, '💔', 'Breakup Expressions', '이별 표현', 'تعبيرات الانفصال', 'Heartbreak and breakup vocabulary.', 'مفردات كسر القلوب والانفصال.', 'kdrama', 2, true),
  (11, '🙏', 'Meeting the Parents', '부모님 인사', 'مقابلة الوالدين', 'Formal greetings and honorifics.', 'التحيات الرسمية والحرمة.', 'kdrama', 2, true),
  (12, '😤', 'Family Conflict', '가족 갈등', 'الصراع الأسري', 'Argument vocabulary and family drama.', 'مفردات الجدال ودراما العائلة.', 'kdrama', 2, true),
  (13, '⚔️', 'Sibling Rivalry', '형제 경쟁', 'التنافس بين الإخوة', 'Sibling tension language.', 'لغة التوتر بين الأشقاء.', 'kdrama', 2, true),
  (14, '👴', 'Generational Differences', '세대 차이', 'الفوارق بين الأجيال', 'Speech levels between generations.', 'مستويات الكلام بين الأجيال.', 'kdrama', 2, true),
  (15, '💰', 'Inheritance Drama', '상속 갈등', 'دراما الميراث', 'Business and inheritance conflict.', 'صراع الأعمال والميراث.', 'kdrama', 2, true),
  (16, '🏢', 'Office Hierarchy', '직장 위계', 'التسلسل الهرمي', 'Ranks, titles, workplace language.', 'الرتب والألقاب ولغة العمل.', 'kdrama', 2, true),
  (17, '📊', 'Work Presentation', '업무 발표', 'العرض التقديمي', 'Workplace presentation vocabulary.', 'مفردات العرض التقديمي.', 'kdrama', 2, true),
  (18, '💌', 'Office Romance', '사내 연애', 'الرومانسية في المكتب', 'Workplace relationships and secrets.', 'علاقات مكان العمل وأسراره.', 'kdrama', 2, true),
  (19, '💢', 'Team Conflict', '팀 갈등', 'صراع الفريق', 'Workplace conflict and resolution.', 'صراع مكان العمل وحله.', 'kdrama', 2, true),
  (20, '👋', 'Resignation and Farewell', '사직과 작별', 'الاستقالة والوداع', 'Dramatic resignation speeches.', 'خطب الاستقالة الدرامية.', 'kdrama', 2, true),
  (21, '🏃', 'Chase Scene', '추격 장면', 'مشهد المطاردة', 'Action vocabulary and commands.', 'مفردات الحركة والأوامر.', 'kdrama', 2, true),
  (22, '🥊', 'Fighting Expressions', '싸움 표현', 'تعبيرات القتال', 'Dramatic fight dialogue.', 'حوار القتال الدرامي.', 'kdrama', 2, true),
  (23, '😱', 'Plot Twist Reactions', '반전 반응', 'ردود فعل التحولات', 'Shock, disbelief, and revelation.', 'الصدمة والتشكيك والكشف.', 'kdrama', 2, true),
  (24, '🚔', 'Police Interrogation', '경찰 심문', 'استجواب الشرطة', 'Law enforcement vocabulary.', 'مفردات إنفاذ القانون.', 'kdrama', 2, true),
  (25, '😈', 'Revenge Monologue', '복수 독백', 'مونولوج الانتقام', 'Revenge expressions and villain speech.', 'تعبيرات الانتقام وخطاب الشرير.', 'kdrama', 3, true),
  (26, '🌮', 'Street Food Scene', '길거리 음식', 'طعام الشارع', 'Order Korean street food.', 'اطلب الطعام الكوري الشعبي.', 'kdrama', 1, true),
  (27, '🍷', 'Restaurant Date', '식당 데이트', 'موعد في المطعم', 'Romantic restaurant vocabulary.', 'مفردات المطعم الرومانسي.', 'kdrama', 1, true),
  (28, '🍳', 'Cooking Together', '함께 요리하기', 'الطبخ معاً', 'Cook together from drama scenes.', 'مفردات الطبخ معاً.', 'kdrama', 1, true),
  (29, '🍺', 'Drinking Culture', '음주 문화', 'ثقافة الشرب', 'Korean drinking customs.', 'الأعراف الكورية في الشرب.', 'kdrama', 2, true),
  (30, '🍱', 'Food as Emotion', '음식과 감정', 'الطعام كمشاعر', 'How K-Dramas use food for love.', 'كيف تستخدم الدراما الطعام للتعبير عن الحب.', 'kdrama', 2, true),
  (1, '📌', 'Subject Particles 이/가 vs 은/는', '주격 조사', 'جسيمات الفاعل', 'The critical topic vs subject distinction.', 'الفرق الجوهري بين الموضوع والفاعل.', 'grammar-mastery', 1, true),
  (2, '🎯', 'Object Particle 을/를', '목적격 조사', 'جسيمة المفعول', 'Mark direct objects correctly.', 'ميِّز المفاعيل بشكل صحيح.', 'grammar-mastery', 1, true),
  (3, '📍', 'Location Particles 에 vs 에서', '장소 조사', 'جسيمات الموضع', 'Static vs active location.', 'الموضع الثابت مقابل الفعّال.', 'grammar-mastery', 1, true),
  (4, '➡️', 'Direction Particle 으로/로', '방향 조사', 'جسيمة الاتجاه', 'Direction, means, and transformation.', 'الاتجاه والوسيلة والتحويل.', 'grammar-mastery', 1, true),
  (5, '🤝', 'Accompaniment Particles', '동반 조사', 'جسيمات المصاحبة', '와/과, 하고, 랑/이랑 in context.', 'جسيمات المصاحبة في السياق.', 'grammar-mastery', 1, true),
  (6, '💼', 'Possession Particle 의', '소유격 조사', 'جسيمة الملكية', 'Use 의 and know when to omit it.', 'استخدم 의 واعرف متى تحذفه.', 'grammar-mastery', 1, true),
  (7, '⭐', 'Special Particles 도, 만', '특수 조사', 'الجسيمات الخاصة', 'Add nuance with 도 (also), 만 (only).', 'أضف دقةً بـ 도 (أيضاً) و만 (فقط).', 'grammar-mastery', 1, true),
  (8, '🧩', 'Particle Combinations', '조사 결합', 'تركيبات الجسيمات', 'Stack: 에서는, 에게도, etc.', 'كوِّم الجسيمات بشكل صحيح.', 'grammar-mastery', 1, true),
  (9, '🔧', 'Verb Conjugation Basics', '동사 활용 기초', 'أساسيات تصريف الأفعال', 'Verb stems and endings.', 'جذور الأفعال والنهايات.', 'grammar-mastery', 1, true),
  (10, '💬', 'Polite Present -아요/어요', '공손한 현재', 'المضارع المهذب', 'Standard polite present tense.', 'صيغة المضارع المهذب القياسية.', 'grammar-mastery', 1, true),
  (11, '⏪', 'Past Tense -았/었어요', '과거 시제', 'الزمن الماضي', 'Form past tense naturally.', 'كوِّن الماضي بشكل طبيعي.', 'grammar-mastery', 1, true),
  (12, '⏩', 'Future -(으)ㄹ 거예요', '미래 시제', 'الزمن المستقبل', 'Future plans and predictions.', 'الخطط والتنبؤات المستقبلية.', 'grammar-mastery', 1, true),
  (13, '🌈', 'Descriptive Verbs as Adjectives', '형용사 활용', 'الأفعال الوصفية', 'Modify nouns with descriptive verbs.', 'عدِّل الأسماء بالأفعال الوصفية.', 'grammar-mastery', 1, true),
  (14, '❌', 'Negation 안 vs -지 않다', '부정 표현', 'أنماط النفي', 'Two negation patterns.', 'نمطان للنفي.', 'grammar-mastery', 1, true),
  (15, '⚠️', 'Irregular Verbs', '불규칙 동사', 'الأفعال غير المنتظمة', 'ㅂ, 르, ㄷ, ㅅ irregulars.', 'الأفعال غير المنتظمة.', 'grammar-mastery', 1, true),
  (16, '🎩', 'Formal Ending -ㅂ니다', '격식체 어미', 'النهاية الرسمية', 'Formal endings for professional use.', 'نهايات رسمية للاستخدام المهني.', 'grammar-mastery', 1, true),
  (17, '🔗', 'Sequential -고', '순차 -고', 'التتابع -고', 'Link actions sequentially.', 'اربط الأفعال التتابعية.', 'grammar-mastery', 2, true),
  (18, '💡', 'Reason -아서/어서', '이유 접속', 'السبب', 'Express reason or sequential cause.', 'عبِّر عن السبب أو السببية.', 'grammar-mastery', 2, true),
  (19, '⚡', 'Contrast -지만', '대조 -지만', 'التناقض', 'Connect contrasting ideas.', 'اربط الأفكار المتناقضة.', 'grammar-mastery', 2, true),
  (20, '🔀', 'Condition -(으)면', '조건 접속', 'الشرط', 'Form if-then conditionals.', 'كوِّن الشرطيات.', 'grammar-mastery', 2, true),
  (21, '⏱️', 'Simultaneous -(으)면서', '동시 접속', 'التزامن', 'Two actions at the same time.', 'فعلان في آنٍ واحد.', 'grammar-mastery', 2, true),
  (22, '🎭', 'Background -(으)ㄴ/는데', '배경 접속', 'الخلفية', 'Set context or mild contrast.', 'ضع السياق أو تناقضاً خفيفاً.', 'grammar-mastery', 2, true),
  (23, '🎯', 'Purpose -(으)러 vs -(으)려고', '목적 접속', 'الغرض', 'Purpose with movement vs intention.', 'الغرض مع الحركة مقابل النية.', 'grammar-mastery', 2, true),
  (24, '🤷', 'Concession -아도/어도', '양보 접속', 'التنازل', 'Even if / although concession.', 'حتى لو / على الرغم من.', 'grammar-mastery', 2, true),
  (25, '😊', 'Informal Speech (반말)', '반말', 'الكلام العامي', 'Plain speech with close friends.', 'الكلام العادي مع الأصدقاء.', 'grammar-mastery', 2, true),
  (26, '🙂', 'Polite Formal 해요체', '해요체', 'الصيغة المهذبة', 'Standard polite form.', 'الصيغة المهذبة القياسية.', 'grammar-mastery', 2, true),
  (27, '🎩', 'Formal 합쇼체', '합쇼체', 'الحرمة الرسمية', 'Highest formal level for broadcasting.', 'أعلى مستوى رسمي.', 'grammar-mastery', 2, true),
  (28, '👑', 'Subject Honorific -시-', '주체 높임 -시-', 'الحرمة الفاعلية', 'Respect the subject with -시-.', 'بجِّل الفاعل بـ -시-.', 'grammar-mastery', 2, true),
  (29, '🙏', 'Object Honorific Vocab', '객체 높임 어휘', 'مفردات الحرمة', 'Special words for elders.', 'كلمات خاصة لكبار السن.', 'grammar-mastery', 2, true),
  (30, '🌸', 'Humble Speech', '겸양어', 'الكلام المتواضع', 'Lower yourself while honoring listener.', 'انزل بنفسك لتكريم المستمع.', 'grammar-mastery', 2, true),
  (31, '💬', 'Honorifics in Reported Speech', '간접화법 높임', 'الحرمة في الكلام المنقول', 'Honorifics in reporting.', 'الحرمة في الإبلاغ.', 'grammar-mastery', 3, true),
  (32, '🎭', 'Navigating Speech Levels', '화계 운용', 'إدارة مستويات الكلام', 'Choose the right level in context.', 'اختر المستوى الصحيح في السياق.', 'grammar-mastery', 3, true),
  (33, '🔄', 'Passive Voice -이/히/리/기-', '피동 접사', 'المبني للمجهول', 'Passive verbs from active stems.', 'أفعال مبنية للمجهول.', 'grammar-mastery', 3, true),
  (34, '🌊', 'Passive -아/어지다', '지다 피동', 'المبني للمجهول بـ 지다', 'Natural passives with -지다.', 'المبني للمجهول الطبيعي.', 'grammar-mastery', 3, true),
  (35, '🎭', 'Causative Suffixes', '사동 접사', 'لواحق التسبب', 'Make someone do something.', 'اجعل شخصاً يفعل شيئاً.', 'grammar-mastery', 3, true),
  (36, '⚙️', 'Causative -게 하다', '-게 하다 사동', 'التسبب بـ -게 하다', 'Flexible causative construction.', 'تركيب التسبب المرن.', 'grammar-mastery', 3, true),
  (37, '▶️', 'Progressive -고 있다', '진행상', '-고 있다 للمستمر', 'Ongoing actions in progress.', 'الأفعال الجارية المستمرة.', 'grammar-mastery', 3, true),
  (38, '🎯', 'Resultative -아/어 있다', '결과상', '-아/어 있다 للحالة', 'States from completed actions.', 'الحالات الناتجة عن أفعال مكتملة.', 'grammar-mastery', 3, true),
  (39, '💨', 'Completion -아/어 버리다', '완료 표현', 'الإتمام', 'Completed actions with regret nuance.', 'الأفعال المكتملة مع ظل الندم.', 'grammar-mastery', 3, true),
  (40, '🌟', 'Experience -아/어 보다', '경험 표현', 'الخبرة', 'Trying or experiencing something.', 'تجربة شيء ما.', 'grammar-mastery', 3, true),
  (41, '💪', 'Ability 할 수 있다/없다', '능력 표현', 'القدرة', 'Ability and inability.', 'القدرة وعدمها.', 'grammar-mastery', 4, true),
  (42, '⚡', 'Obligation -아/어야 하다', '의무 표현', 'الوجوب', 'Must and obligation.', 'الوجوب والضرورة.', 'grammar-mastery', 4, true),
  (43, '🚫', 'Prohibition -면 안 되다', '금지 표현', 'النهي', 'Prohibition and what must not happen.', 'النهي وما يجب ألا يحدث.', 'grammar-mastery', 4, true),
  (44, '✅', 'Permission -아/어도 되다', '허가 표현', 'الإذن', 'Ask for and grant permission.', 'اطلب الإذن وامنحه.', 'grammar-mastery', 4, true),
  (45, '💭', 'Desire -고 싶다', '바람 표현', 'الرغبة', 'Personal desires and wishes.', 'الرغبات الشخصية والأمنيات.', 'grammar-mastery', 4, true),
  (46, '💡', 'Suggestions -(으)ㄹ까요', '제안 표현', 'الاقتراحات', 'Make suggestions and recommendations.', 'قدِّم اقتراحات وتوصيات.', 'grammar-mastery', 4, true),
  (47, '💎', 'Common Korean Idioms', '일반 관용구', 'الاصطلاحات الشائعة', 'Body-part idioms and fixed expressions.', 'اصطلاحات أجزاء الجسم.', 'grammar-mastery', 5, true),
  (48, '📜', 'Korean Proverbs', '한국 속담', 'الأمثال الكورية', 'Classic proverbs and modern usage.', 'الأمثال الكلاسيكية واستخدامها.', 'grammar-mastery', 5, true),
  (49, '🔤', 'Four-Character Idioms', '사자성어', 'الاصطلاحات الرباعية', 'Sino-Korean four-character expressions.', 'التعبيرات الصينية الكورية الرباعية.', 'grammar-mastery', 5, true),
  (50, '🌸', 'Metaphor and Simile', '은유와 직유', 'الاستعارة والتشبيه', 'Figurative language in Korean.', 'اللغة المجازية بالكورية.', 'grammar-mastery', 5, true),
  (51, '😏', 'Irony and Sarcasm', '아이러니와 풍자', 'السخرية والتهكم', 'Recognize and produce irony.', 'تعرف على السخرية وأنتجها.', 'grammar-mastery', 5, true),
  (52, '🎯', 'Emphatic Patterns', '강조 표현', 'الأنماط التأكيدية', 'Rhetorical questions and parallelism.', 'الأسئلة البلاغية والتوازي.', 'grammar-mastery', 5, true),
  (53, '📜', 'Classical Grammar Endings', '고전 문법 어미', 'نهايات القواعد الكلاسيكية', 'Literary endings -노라, -로다, -리라.', 'النهايات الأدبية الكلاسيكية.', 'grammar-mastery', 6, true),
  (54, '🏛️', 'Archaic Vocabulary', '고어 어휘', 'المفردات العتيقة', 'Old Korean in literature and proverbs.', 'الكورية القديمة في الأدب والأمثال.', 'grammar-mastery', 6, true),
  (55, '🆕', 'Neologisms and Slang', '신조어와 속어', 'الكلمات الجديدة والعامية', 'New vocab from internet and youth.', 'مفردات جديدة من الإنترنت والشباب.', 'grammar-mastery', 6, true),
  (56, '🔄', 'Translation Grammar Patterns', '번역 문법 패턴', 'أنماط قواعد الترجمة', 'Patterns that challenge translators.', 'الأنماط التي تتحدى المترجمين.', 'grammar-mastery', 6, true),
  (57, '🌟', 'Grammar Mastery Final Review', '문법 마스터리 총복습', 'المراجعة النهائية', 'Complete review of all 57 patterns.', 'مراجعة كاملة لـ 57 نمطاً.', 'grammar-mastery', 6, true)
ON CONFLICT (book, sort_order) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ko = EXCLUDED.title_ko,
  title_ar = EXCLUDED.title_ar,
  description = EXCLUDED.description,
  description_ar = EXCLUDED.description_ar,
  emoji = EXCLUDED.emoji,
  topik_level = EXCLUDED.topik_level,
  is_published = EXCLUDED.is_published;